name: COBOL Check Automation

on:
  push:
    branches: [ main ]

jobs:
  cobol-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Zowe CLI
        run: npm install -g @zowe/cli

      - name: Run Zowe Operations Script
        env:
          ZOWE_USERNAME: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
          ZOSMF_HOST: ${{ secrets.ZOSMF_HOST }}
          ZOSMF_PORT: ${{ secrets.ZOSMF_PORT }}
          ZOWE_ZOSMF_HOST: ${{ secrets.ZOSMF_HOST }}
          ZOWE_ZOSMF_PORT: ${{ secrets.ZOSMF_PORT }}
          ZOWE_ZOSMF_USER: ${{ secrets.ZOWE_USERNAME }}
          ZOWE_ZOSMF_PASSWORD: ${{ secrets.ZOWE_PASSWORD }}
        run: |
          chmod +x .github/scripts/zowe_operations.sh
          .github/scripts/zowe_operations.sh